Repository jupyter-widgets/ipywidgets, pull requests merged in 2021-09, with the labels that each got.

#3265 Add new trove classifiers for JLab extensions
  jupyterlab_widgets/setup.cfg
Labels: backport

#3272 Fix tagsinput initial display
  docs/source/examples/Widget List.ipynb
  ipywidgets/widgets/widget_tagsinput.py
  packages/controls/src/widget_tagsinput.ts
  packages/schema/jupyterwidgetmodels.latest.json
  packages/schema/jupyterwidgetmodels.latest.md
Labels: bug

#2834 Add dragging behaviour properties to sliders
  docs/source/examples/Output Widget.ipynb
  docs/source/examples/Widget Styling.ipynb
  ipywidgets/widgets/widget_float.py
  ipywidgets/widgets/widget_int.py
  ipywidgets/widgets/widget_selection.py
  packages/controls/src/widget_float.ts
  packages/controls/src/widget_int.ts
  packages/controls/src/widget_selection.ts
  packages/schema/jupyterwidgetmodels.latest.md
Labels: needs discussion

#3283 Fix docs's "process is not defined" issue
  packages/html-manager/webpack.config.js
Labels: docs
