Repository jupyter-widgets/ipywidgets, pull requests merged in 2022-08, with the labels that each got.

#3536 Use JupyterLuminoPanelWidget for html manager output widget's lumino widget
  packages/base/src/widget.ts
  packages/html-manager/src/output.ts
  python/jupyterlab_widgets/package.json
  python/jupyterlab_widgets/src/output.ts
Labels: backport

#3548 Update to lerna 5.4.3
  package.json
  yarn.lock
Labels: maintenance

#3549 Deserialize state before setting it, as is done elsewhere set_state is used
  packages/base-manager/src/manager-base.ts
Labels: backport

#3551 [7.x] Pin to `jupyterlab_widgets>=1.0.0,<3`
  .github/workflows/build.yml
  dev-install.sh
  setup.py
Labels: maintenance

#3554 Tweak some typings
  packages/base/src/utils.ts
  packages/base/src/widget.ts
Labels: pkg:base

#3568 Fix slider update on readout text change
  packages/controls/src/widget_float.ts
  packages/controls/src/widget_int.ts
Labels: bug
