Repository jupyter-widgets/ipywidgets, pull requests merged in 2022-02, with the labels that each got.

#3370 Allow Output widget in html manager to render state updates
  examples/web3/jupyter-logo.svg
  examples/web3/widget_code.json
  packages/html-manager/src/output.ts
  packages/html-manager/test/src/output_test.ts
Labels: backport

#3338 Documentation: Custom Widgets – Passing URLs
  docs/source/examples/Widget Custom.ipynb
Labels: documentation

#3335 Use control comm target in base Manager
  packages/base-manager/src/manager-base.ts
  python/jupyterlab_widgets/src/manager.ts
  python/widgetsnbextension/src/manager.js
Labels: enhancement

#3367 Fix downward arrow misalignment for combobox
  packages/controls/css/widgets-base.css
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-10-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-11-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-24-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-25-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-26-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-27-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-28-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-29-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-30-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-31-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-32-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-33-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-34-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-35-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-36-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-37-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-38-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-39-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-40-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-41-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-42-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-43-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-8-linux.png
  ui-tests/tests/widgets.test.ts-snapshots/widgets-cell-9-linux.png
Labels: backport

#2975 Bugfix: fix return key submission of IntText widgets
  packages/controls/src/widget_int.ts
Labels: bug, ux/ui, pkg:controls
